### ISSUE TITLE
import ecco_v4_py as ecco not working

### ISSUE THREAD

**Issue by JustinWenzhaoLi** [ECCO-GROUP/ECCOv4-py#101]
Will return:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-c08a9f7e399d> in <module>()
----> 1 import ecco_v4_py as ecco

8 frames
/usr/lib/python3.6/inspect.py in cleandoc(doc)
    618     onwards is removed."""
    619     try:
--> 620         lines = doc.expandtabs().split('\n')
    621     except UnicodeError:
    622         return None

AttributeError: 'NoneType' object has no attribute 'expandtabs'

**Comment by jetesdal** [comment]
Hi @JustinWenzhaoLi, I suspect it's the same reason as described here: https://github.com/xgcm/xgcm/issues/210

**Comment by timothyas** [comment]
Hey there, sorry for the delay on this! I just merged a fix to our package which calls the correct version of xgcm, which specifies docrep<=0.2.7. We will try to release this version to pip and conda-forge soon, but in the meantime you can always get the most recent version of this repo by cloning or through pip via:

```
pip install git+https://github.com/ECCO-GROUP/ECCOv4-py.git
```

I'll wait until we have a new version on pip, and that version works before closing this.

**Comment by timothyas** [comment]
Hey @JustinWenzhaoLi, we just recently released a new version of ecco_v4_py on pip. Does this solve the original problem?

Thanks for your patience!

**Comment by timothyas** [comment]
I will go ahead and close this since this was addressed with the latest release, but please feel free to reopen it or open a new issue if the problem persists.
