### ISSUE TITLE
How to make a grid nc file like the "ECCO-GRID.nc" for LLC 270

### ISSUE THREAD

**Issue by liu-ran** [ECCO-GROUP/ECCOv4-py#102]
The ECCO-GRID.nc is required for many functions in ECCOv4-py. My question is how to make a similar grid file for LLC270. My MITgcm simulation will output more than 300 grid*.nc files due to the CPU number. How to glue these grid*.nc files into one file like the ECCO-GRID.nc?

**Comment by liu-ran** [comment]
The binary outputs of MITgcm don't include the information: i,j,i_g,j_g,k,k_l,k_u,k_p1, which are necessary for vector rotation, so that the outputs have to be written as the *.nc files which include the above information. But these grid*.nc files cannot be opened by the routine  'ecco.load_ecco_grid_nc' because it only support something like : ECCOv4r3_grid.nc or ECCOv4r4_grid.nc.

**Comment by timothyas** [comment]
Hey @liu-ran, I apologize that this is a bit confusing. Just to clarify, are you running the LLC 270 with the MITgcm and writing output using the netcdf capabilities of the MITgcm? If so, then I would instead use the mdsio package. Then, you can simply point [load_ecco_vars_from_mds](https://github.com/ECCO-GROUP/ECCOv4-py/blob/e8dc991facb4a33829ecdf5ecbb1b4b7767f393f/ecco_v4_py/read_bin_llc.py#L31) to this directory (or you can use [open_mdsdataset](https://xmitgcm.readthedocs.io/en/latest/usage.html) directly, as the former is a wrapper for the latter). 

For example... 

```
ds = open_mdsdataset('/path/to/run/directory',geometry='llc',iters=None)
```

and this will give you a nice dataset with all of the grid information, then you can create an xgcm grid object with this for performing grid operations as follows: 

```
grid = ecco_v4_py.get_llc_grid(ds)
```

See more at [xgcm](https://xgcm.readthedocs.io/en/latest/example_eccov4.html#)

Also if you want to load diagnostics from a different directory at the same time... 

```
ds = open_mdsdataset(data_dir='/path/to/diagnostics',grid_dir='/path/to/run/directory/with/grid/meta/data',
geometry='llc',delta_t=my_timestep,ref_date='1992-01-01')
```

Note that `delta_t` and `ref_date` are optional but make the time vector nice. Please let me know if I misinterpreted what you're asking. I hope that helps!

**Comment by liu-ran** [comment]
Many thanks! @timothyas  open_mdsdataset worked well. But get_llc_grid(ds) failed and there exists some assertionError as shown in the following pictures
![微信图片_20200912122758](https://user-images.githubusercontent.com/48266323/92987289-ba6a9980-f4f3-11ea-9645-b2117fcc780c.png)
![微信图片_20200912122804](https://user-images.githubusercontent.com/48266323/92987291-c2c2d480-f4f3-11ea-8e20-89da32912cd1.png)

**Comment by timothyas** [comment]
Ah! I forgot. Ecco_v4_py and xmitgcm differ on what we call “faces”. An xmitgcm “face” is an ecco_v4_py “tile”. This is simple to fix though:

```
ds = ds.rename({“face”:”tile”})
```

This is performed in the wrapper [load_ecco_vars_from_mds](https://github.com/ECCO-GROUP/ECCOv4-py/blob/e8dc991facb4a33829ecdf5ecbb1b4b7767f393f/ecco_v4_py/read_bin_llc.py#L31)

**Comment by liu-ran** [comment]
Great! Thank you!

**Comment by timothyas** [comment]
No problem! Glad to help! 

If that fixed your issue, can we close this one?

**Comment by liu-ran** [comment]
That's ok.
