### ISSUE TITLE
Doc missing for interpolating ECCO vectors to lat-lon grids?

### ISSUE THREAD

**Issue by ggebbie** [ECCO-GROUP/ECCOv4-py#119]
Thanks to all the developers for the great work on ECCOv4-py!   I'm trying to locate info on how ECCO vector fields have been interpolated on to lat-lon grids for variables such as EVEL* and NVEL*.  I had an old link to:

https://ecco-v4-python-tutorial.readthedocs.io/ECCO_v4_Interpolating_Fields_to_Lat-Lon_Grid.html#Interpolating-ECCO-vectors-fields-to-lat-lon-grids

but now it displays `<no title>` in my browser. Am I missing an updated link or has this doc page been removed?   Thanks -- and apologies if this was buried in a previous issue.

**Comment by ggebbie** [comment]
Thanks so much, Tim.  These are just the details that I was wondering about. Yes, I have UVEL* and VVEL* on hand. In the future, it looks like I can output EVEL* and NVEL* from the MITgcm diags package directly.

**Comment by timothyas** [comment]
No problem! Glad that is helpful. Yeah, the diags package may also be how ECCO's evel/nvel are produced, but I'm not exactly sure.
