### ISSUE TITLE
Unnecessary dependencies in setup.py

### ISSUE THREAD

**Issue by rcaneill** [ECCO-GROUP/ECCOv4-py#134]
Hello,
thanks for this very nice package!
While trying to install it via poetry (that uses pip internally), I had some issues. After some research, I think this is because some unnecessary deps are defined in the setup files. These deps are:
* proj (installing via pip tries to install https://pypi.org/project/proj/ , which is not the same as https://proj.org/ packaged in anaconda)
* geos (installing via pip installs https://pypi.org/project/geos/)
* pathlib (is part of the python standard lib, and installing from pip tries to use an old unmaintained version from 2014) (although it seems that this one will be removed from the setup.py of the next ecco-v4-py release)

Apart from my troubles installing via poetry (due to pathlib), this installs a lot of useless packages.

I can submit a PR to fix this issue if you want to.

https://github.com/ECCO-GROUP/ECCOv4-py/blob/3960799927dc9f8ecd4b1d7a4138caffe9814e31/setup.py#L24-L28

**Comment by ifenty** [comment]
Hi Romain @rcaneill 

Thank you for the comment.  I think you are right about pathlib -- I didn't realize it was part of standard python deployments. At one point proj and geos were needed by cartopy or pyresample.  Are you saying that proj and geos are no longer required? If that's true, then let's remove them from setup.py.

Ian

**Comment by rcaneill** [comment]
Proj and geos are still required by cartopy, however not the pip libraries (that are completely other things, cf my previous comment), but the binaries libraries (installable via e.g. conda or apt-get). So I guess that they should be removed from setup.py

**Comment by ifenty** [comment]
@rcaneill I removed *geos*, *proj*, and *pathlib* per your suggestion. If installation via poetry still fails with the new version (1.5.4) let's figure out why.

**Comment by rcaneill** [comment]
Works fine now, with the version 1.5.4.
Thanks!
