### ISSUE TITLE
duplicative functionality in ECCOv4-py

### ISSUE THREAD

**Issue by rabernat** [ECCO-GROUP/ECCOv4-py#2]
Thanks again for getting the ball rolling on this important package!

I just had a look through the source code and noticed a few main areas where there is duplicate functionality with other packages:
- The [mds_io module](https://github.com/ECCO-GROUP/ECCOv4-py/blob/master/ecco_v4_py/mds_io.py) duplicates [xmitgcm.utils.read_3d_llc_data](http://xmitgcm.readthedocs.io/en/latest/utils.html#xmitgcm.utils.read_3d_llc_data). There are some differences of course (the xmitgcm version is more generic and also uses dask to make the operation lazy), but the basic goal is the same.
- The [tile_exchange module](https://github.com/ECCO-GROUP/ECCOv4-py/blob/master/ecco_v4_py/tile_exchange.py) partially duplicates the exchange capabilities introduced in xgcm via xgcm/xgcm#88.

Given the complexity of these routines, it would be best to just have to write and maintain them in one place.

**Comment by ifenty** [comment]
reading MITgcm mds files now leverages xmitgcm capabilities.

specifically, the routine **load_ecco_vars_from_mds** extends xmitgcm's **open_mdsdataset** for cases when the output fields are daily, weekly, or monthly time mean fields.  specifically, when the output fields are time means, the *time* attributed is changed to reflect the center of the averaging time period (e.g., the middle of the calendar month over which the monthly time-average was take)   and a new attribute *time_bnds* is added which indicates the beginning and end of the averaging period.
