### ISSUE TITLE
Generic behavior with ASTE / global llc grids

### ISSUE THREAD

**Issue by timothyas** [ECCO-GROUP/ECCOv4-py#38]
This repository is currently designed to work with global llc grids, and by default the global llc90 grid as used in ECCOv4. However, it would be even more useful if we made it flexible to include various regional configurations with the LLC configuration, e.g. ASTE. This would allow us to merge in @raphaeldussin's MITgcm-recipes repo. For instance his regridding, open boundary routines, etc are a huge service to the community that I'm sure a lot of folks would benefit from. 

Thanks to the flexibility of xmitgcm and xgcm, I think the only functions that need changing are: 
- [ecco_utils.get_llc_grid](https://github.com/ECCO-GROUP/ECCOv4-py/blob/master/ecco_v4_py/ecco_utils.py): this defines the xgcm grid object with all of the LLC connections (note that in ECCO terms, the xgcm "face" dimension is renamed to "tile", because "face" refers to something specific in the gcmfaces package). @raphaeldussin has done this [here](https://github.com/raphaeldussin/MITgcm-recipes/blob/master/MITgcm_recipes/utils.py) for ASTE
- [read_bin_llc.load_ecco_vars_from_mds](https://github.com/ECCO-GROUP/ECCOv4-py/blob/master/ecco_v4_py/read_bin_llc.py): this is basically a wrapper around [xmitgcm.open_mdsdataset](https://github.com/xgcm/xmitgcm/blob/master/xmitgcm/mds_store.py), but specifies some nice things like the reference date, time step, etc... and renames the face-> tile dimension. Also, one can load specific tiles and change the time step location based on time averaging etc. 
- the [llc_array_conversion](https://github.com/ECCO-GROUP/ECCOv4-py/blob/master/ecco_v4_py/llc_array_conversion.py) routines may need some fixing, but I don't think they're critical. In fact, the convert_tiles_to_xda function doesn't need to be changed, only the routines which convert between faces, compact, and tiles formats. 

Specifically moving forward with ASTE, I think that we should make some of these changes by adding a flag such as "model_config" which has by default model_config='global', but could be changed to e.g. model_config='aste' to set up these different configurations.

I am happy to help start making these merges in my spare time. But I think @lauren-moseley would benefit a lot from helping out with this because you'll be working with ASTE - I haven't done anything with ASTE :) I suggest @lauren-moseley because I can imagine that @raphaeldussin is pretty swamped at the moment with job transition.

**Comment by ifenty** [comment]
Tim,
On one hand this  package was created to help people use and analyze the the global ECCO v4 llc solution and so supporting regional domains seems out of scope.  On the other hand, duplicating functionality for a separate ASTE package would be terribly wasteful -- analysis routines that work for the global llc90 fields are going to be essentially the same for regional llc cut-outs.  

I looked at Ralph's code for loading ASTE and thought that it brought things in with 5 faces of different sizes.  In ecco_v4_py the decomposition is with tile so I think we'd have 6 tiles (right?) with some at least two of the tiles with some zero padding.

Also, I had to spend considerable time reverse-engineering how ASTE files were saved because I couldn't find it documented anywhere.  Clearly documenting the formatting of 'compact' files in reginal llc domains would be a service to others.  

The conversion routines work on numpy arrays assuming 13xllcxllc.  For them to work with fewer I think we would just need to specify which were being passed as a separate argument.

**Comment by timothyas** [comment]
Yep agreed, it looks like the [convention for ASTE is 6 tiles in ecco_v4_py lingo or faces in xmitgcm lingo](https://github.com/raphaeldussin/MITgcm-recipes/blob/master/MITgcm_recipes/utils.py)

As for the `llc_array_conversion` routines, it looks like @raphaeldussin has done this at least for faces->tiles (which he has called facets->faces) [here](https://github.com/raphaeldussin/MITgcm-recipes/blob/master/MITgcm_recipes/data_organization.py). Perhaps there is a "compact" conversion somewhere in there. 

I'm not sure the best way to merge these routines, or routines in the `tile_plot` module, which are very hard coded for 13 tiles. It would be tempting to make an `llc_array_conversion_aste` module, but this could be a devious path as we could end up with a proliferation of modules for every regional model in the ECCO umbrella. There has to be a more general path, or maybe ASTE users are fine with just using the tile format and not converting to compact, in which case there would be a relatively minimal impact since all routines that are based around xmitgcm will work fine (thanks to @raphaeldussin's work), as well as the calc_*, tile_plot_proj. 

My original comment came out of a zoom call with @raphaeldussin and @lauren-moseley, so I'd be interested in what they and any other ASTE user thinks (although maybe Raph won't be an ASTE user for very long?). I don't really work with ASTE, so I can't focus a ton of time on this. But I'd be happy to help think about the best way forward.

**Comment by ifenty** [comment]
converting from ASTE tiles to the equivalent compact format wasn't super obvious to me but actually is shockingly simple once you realize what is meant by "c convention" vs " fortran convention" in the documentation.   At least one version of ``tile_plot`` can handle subsets of the 13 tiles stored in``DataArrays`` provided that the ``tile`` coordinate was populated.  Tiles that are not present are skipped, so actually that's not a big deal.
