### ISSUE TITLE
Installation guide issues

### ISSUE THREAD

**Issue by timothyas** [ECCO-GROUP/ECCOv4-py#4]
Hey @ifenty thanks so much for this python package and the great documentation! I recently found it and have been going through the examples. It's a great start for breaking my MATLAB addiction ...  

I just wanted to make a couple notes:

- basemap can no longer be installed via pip. Instead, users are directed via the [basemap github readme](https://github.com/matplotlib/basemap) to download a tar ball from [the basemap release page](https://github.com/matplotlib/basemap/releases) 

- on their website they recommend building geos-3.3, but this was a pain. I had a much easier time using the mac package manager [Homebrew](https://brew.sh/). The command `brew install geos` did the trick.

- I had trouble downloading pyresample via pip on my mac because of an openmp requirement.  However conda took care of it with the command:`conda install -c conda-forge pyresample`

**Comment by ifenty** [comment]
Tim, thanks for these suggestions.  I updated the ecco instructions based on your suggestions.

Ian
