### ISSUE TITLE
netcdf_product_generation.py

### ISSUE THREAD

**Issue by owang01** [ECCO-GROUP/ECCOv4-py#40]
netcdf_product_generation.py calls load_ecco_vars_from_mds to load grid and MDS diagnostics output. The order of arguments in calling load_ecco_vars_from_mds is not correct. Specifically, the second and third arguments should be swapped to be consistent with what is defined in load_ecco_vars_from_mds.: the second and third arguments should be the grid directory name and MDS filename, respectively.

**Comment by timothyas** [comment]
#41 closes #40
