### ISSUE TITLE
'Faroe Scotland' is included in the get_available_sections() but not included in get_section_endpoints()

### ISSUE THREAD

**Issue by jetesdal** [ECCO-GROUP/ECCOv4-py#62]
get_section_endpoints() returns and error for 'Faroe Scotland'. I think this is because the coordinates for this section is actually not included in the function. I assume that the info exists but was accidentally removed.

**Comment by timothyas** [comment]
Good catch! Yep it seems that one slipped through the cracks.

**Comment by timothyas** [comment]
Hey @jetesdal: if you get a fresh checkout of the code it will be there now. Thanks for reporting this one!
