### ISSUE TITLE
file paths

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCOv4-py#75]
In several I/O routines we assume that the user is on a *nix machine where the forward slash '/' separates directories and filenames. This assumption is made when construction full filepaths to load.  For example, in load_binary_array.py we have this line: 
`` datafile = fdir + '/' + fname``

It turns out that on windows machines this method of constructing filepaths fails because windows machines use backslashes.  

It looks like a good solution for Python 3.4 is a library called ``pathlib``.  This library allows easy construction of filepaths independent of operating system.  See this blog post.

https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f

So, we have to go through and replace a bunch of hard coded "path + '/' + filename" with the syntax offered by pathlib.

**Comment by timothyas** [comment]
Good call @ifenty! pathlib looks super handy, much more convenient than the os operations. Shouldn't be a hard fix, and this is something I could do while code is compiling...

**Comment by ifenty** [comment]
@timothyas 

I updated the code to make use of the pathlib library (which is my favorite thing this week) and will make a pull request once I verify that the tutorials work with these changes.

**Comment by timothyas** [comment]
Nice @ifenty! I played with it for just a little while but couldn't figure out how to print the right string no matter the OS. I'm looking forward to it!

**Comment by ifenty** [comment]
make the path using something like: 

``foo_path = Path('/home/timothyas/foo')``

then you can do 

``str(foo_path)``

and that will change depending on your OS.

Also you add a filename to a path like this:

``foo_file = foo_path / 'some_ecco_field_that_is_exactly_what_I_need_for_my_research.nc'``

and not that it's a forward slash regardless of OS.  Then you can do something like:

``foo = xr.open_dataset(str(foo_file))``

**Comment by timothyas** [comment]
Oh that's so simple. Thanks @ifenty!
