### ISSUE TITLE
read_bin_gen.py not working

### ISSUE THREAD

**Issue by owang01** [ECCO-GROUP/ECCOv4-py#82]
read_bin_gen.py broke after a recent update of introducing the "pathlib" package. 

The error occurs at line 80:
f = open(datafile, 'rb')
with the following error message:
TypeError: coercing to Unicode: need string or buffer, PosixPath found

The error is probably because "datafile" is not a string. A possible fix would be to convert "datafile" to a string, like
f = open(str(datafile), 'rb')

**Comment by timothyas** [comment]
Hey @owang01 is this still a problem? I did not notice it to be an issue while working on #106

**Comment by owang01** [comment]
@timothyas Thank you for getting back to this. It is still an issue if one uses Python 2.

**Comment by timothyas** [comment]
Ah good to know, thanks @owang01. Are you using python 2? I didn't even think the package was compatible with python 2, and in general python itself [has already stopped maintaining python 2](https://www.python.org/doc/sunset-python-2/)
