### ISSUE TITLE
Reorient/rotate tools

### ISSUE THREAD

**Issue by christophernhill** [ECCO-GROUP/ECCOv4-py#9]
@ifenty and @timothyas 

Possibly relevant to the reorient/regrid u,v discussion -- I came across this [https://github.com/pletzer/mint](https://github.com/pletzer/mint) by Alex Pletzer (now in New Zealand). Oliver and I are taking  a look to see if it can do local divergence preserving grid transformations. In theory line integral approaches look like they can do this, but until now everyone seems to have been wary of the coding involved when they hear the details. 

Not sure how it handles bathymetry (Alex examples look atmospheric).

**Comment by timothyas** [comment]
This looks interesting. I'll have to look into the details about how this works and what application this is useful for (if you have any refs that would be awesome!) - is this necessary for a simple u/v rotation e.g. for plotting?

**Comment by maikejulie** [comment]
For plotting  @raphaeldussin has done some really nice work for [ASTE](https://github.com/raphaeldussin/MITgcm-recipes/blob/master/examples/Plotting_ASTE.ipynb)

**Comment by christophernhill** [comment]
@timothyas there is an article here https://doi.org/10.1175/MWR-D-18-0146.1
We can also call Alex if useful?
